#!/bin/bash

bin="$HOME/.local/bin"
config="$XDG_CONFIGHOME/fzfx"

doInstall() {
    # Install binaries
    mkdir -p "$bin"
    cp fzfx "$bin/"

    # Install config
    mkdir -p "$config"
    cp -n config ignore "$config/"
}

doUninstall() {
    rm -rf "$bin/fzfx"
}

case $1 in
	install) doInstall;;
	uninstall) doUninstall;;
esac


